// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhOZ82_ai69jt8ylcUFILCqSRl6MXUeBc',
    appId: '1:747945249445:web:63b9e085250e7d626c5b4c',
    messagingSenderId: '747945249445',
    projectId: 'indiespot-7d691',
    authDomain: 'indiespot-7d691.firebaseapp.com',
    storageBucket: 'indiespot-7d691.appspot.com',
    measurementId: 'G-BYZ618CQYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAEerXfvy9qSD_etVmxm4ymhj8bP8q9Qc',
    appId: '1:747945249445:android:585efff7364ef9166c5b4c',
    messagingSenderId: '747945249445',
    projectId: 'indiespot-7d691',
    storageBucket: 'indiespot-7d691.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCs6nbUs4bdHuaNrmvQr5mPhyQpaWF9h8',
    appId: '1:747945249445:ios:a880eda2a30fb3586c5b4c',
    messagingSenderId: '747945249445',
    projectId: 'indiespot-7d691',
    storageBucket: 'indiespot-7d691.appspot.com',
    iosBundleId: 'com.example.indieSpot',
  );
}
